### ISSUE TITLE
would like to have an option to change Actor properties

### ISSUE THREAD

**Issue by dogbiteshoham** [ashblue/fluid-dialogue#43]
in order to expand the usability of the dialogue system I would like to have an option to change how the actor is built.
for example make it load a prefab instead of a sprite.
right now changing such things is difficult because of how the package is built.

stuff i would like to have access to.
1.change sprite to prefab
2.in the dialogue\ choice being able to set the state of so called prefab( make the actor angry,sad...)
3. being able to have several actors on the screen, where one is active and the other is inactive for example.
4. being able to create nodes other than what we have.

**Comment by ashblue** [comment]
@dogbiteshoham well the actor is just an object so there's no reason you can't recast it to have all the same criteria you're looking for. Those are implementation specific details you can add as an action to change the mood on the character.

1. Should be able to accomplish this by adding your own actor implementation or interface https://github.com/ashblue/fluid-dialogue/blob/develop/Assets/com.fluid.dialogue/Runtime/Actors/IActor.cs
2. Should be able to do this with an action for now. Not as nice as built in functionality I know. Something I've considered allowing to be extended so you could add whatever props you want. In the backlog and might happen at some point. Another option is forking the project and adding in your own moods enum. Hard to make a solution that works for everyone's needs since each game needs specific things.
3. You can do that with actions or just make the last person who spoke active
4. Hmmm, Fluid Dialogue just wasn't built with this in mind. You might be able to extend things to do this. It's really not designed for procedurally generating new nodes, but you could probably fork the project if needed. Check out the runtime controller for assembling the node logic

**Comment by ashblue** [comment]
Haven't heard an update so I'm gonna close this out. Please feel free to open a new ticket or feel free to reach out on Discord.
